version: '3.8'

services:
  mysql:
    image: mysql:9.3.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@assword1234
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: P@assword1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
