import type { Metadata } from "next";
import "./globals.css";
import { kanit } from "./fonts";
import { AppHeader } from "./components/app/AppHeader";
import AppContent from "./components/app/AppContent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <AppHeader />
        <AppContent/>
        {children}
      </body>
    </html>
  );
}
